### ISSUE TITLE
Static typing: type inconsistency with BaseEnvelope and DictWrapper

### ISSUE THREAD

**Issue by efrquerido** [awslabs/aws-lambda-powertools-python#1101]
### Static type checker used

{"label"=>"mypy (project's standard)"}

### AWS Lambda function runtime

{"label"=>"3.8"}

### AWS Lambda Powertools for Python version

1.20.2

### Static type checker info

Argument 1 to "APIGatewayProxyEvent" has incompatible type "Union[Dict[str, Any], Any, None]"; expected "Dict[str, Any]"mypy(error)

### Code snippet

```python
class SomeEnvelope(BaseEnvelope):

    def parse(self, data: Optional[Union[Dict[str, Any], Any]], model: Type[Model]) -> Optional[Model]:

        parsed_env = APIGatewayProxyEvent(data)
        data = dict(
            headers=parsed_env.headers or {},
            http_method=parsed_env.http_method,
            path=parsed_env.path,
            path_parameters=parsed_env.path_parameters or {},
            query_parameters=parsed_env.query_string_parameters or {},
            body=json.loads(parsed_env.body) if parsed_env.body else None,
        )
        return self._parse(data=data, model=model)
```

### Possible Solution

update DictWrapper into receiving `Optional[Union[Dict[str, Any], Any]]`

**Comment by heitorlessa** [comment]
Hey @efrquerido - If I recall correctly we fixed this and another related type mismatch for Envelopes a few releases ago, could you check using the latest version, please?

We're at 1.25.7 now

**Comment by efrquerido** [comment]
hey @heitorlessa, just tested with the latest version `'.25.7` and I'm still getting the same error.

I've checked ant the problem seems to be on the __ini__ fo DictWrapper.

APIGatewayProxyEvent --> BaseProxyEvent --> DictWrapper

This is DictWrapper on latest:

`class DictWrapper:
    """Provides a single read only access to a wrapper dict"""

    def __init__(self, data: Dict[str, Any]):
        self._data = data

    def __getitem__(self, key: str) -> Any:
        return self._data[key]

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, DictWrapper):
            return False

        return self._data == other._data

    def get(self, key: str) -> Optional[Any]:
        return self._data.get(key)

    @property
    def raw_event(self) -> Dict[str, Any]:
        """The original raw event dict"""
        return self._data`

**Comment by michaelbrewer** [comment]
@heitorlessa @efrquerido - but `APIGatewayProxyEvent` was built to except the original raw dict event and not the Pydantic version.

If you are using Pydantic, then why not stick to `ApiGatewayEnvelope`, but if you still want both, then maybe convert data to a dict?

**Comment by heitorlessa** [comment]
> hey @heitorlessa, just tested with the latest version `1.25.7` and I'm still getting the same error.
> 
> I've checked ant the problem seems to be on the `__ini__` of DictWrapper.
> 
> APIGatewayProxyEvent --> BaseProxyEvent --> DictWrapper
> 
> This is DictWrapper's `__init__` on latest version:
> 
> ` def __init__(self, data: Dict[str, Any]): self._data = data`

Let's take a step back: what are you trying to achieve? Mypy and the types are correct, as you're accidentally using the incorrect class - `APIGatewayProxyEvent` instead of `APIGatewayProxyEventModel` which is a [Pydantic model in itself](https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/parser/#built-in-models).

```python
from aws_lambda_powertools.utilities.parser.models import APIGatewayProxyEventModel
# Or if using HTTP API with v2 payload
# from aws_lambda_powertools.utilities.parser.models import APIGatewayProxyEventV2Model
```

Understanding what you're after will help us provide a more accurate solution.

Look forward to hearing from you :)

**Comment by heitorlessa** [comment]
Opa @efrquerido - following up with you whether you had this resolved, or if you need any further assistance.
